---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by archine.
--- DateTime: 2019/6/24 14:59
---
local key = KEYS[1]
local val = KEYS[2]
local expire = KEYS[3]
if redis.call("setNx", key, val) == 1 then
    redis.call("expire", key, expire)
    return val
else
    return nil
end