---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by archine.
--- DateTime: 2019/6/24 14:59
---
local key = KEYS[1]
local val = KEYS[2]
if redis.call("get", key) == val then
    local delNum = redis.call("del", key)
    if delNum == 1 then
        return key
    else
        return nil
    end
else
    return nil
end